# Generated by Django 3.2 on 2024-01-07 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_alter_recomments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='fighting',
            field=models.ManyToManyField(related_name='challenge_fighting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='fire',
            field=models.ManyToManyField(related_name='challenge_fire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='good',
            field=models.ManyToManyField(related_name='challenge_good', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='heart',
            field=models.ManyToManyField(related_name='challenge_heart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='mark',
            field=models.ManyToManyField(related_name='challenge_mark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='question',
            field=models.ManyToManyField(related_name='challenge_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
